[2025-10-06T04:35:53.856+0000] {processor.py:161} INFO - Started process (PID=84) to work on /opt/airflow/dags/airflow.py
[2025-10-06T04:35:53.859+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T04:35:53.862+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:35:53.862+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T04:35:53.906+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:35:53.900+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 2, in <module>
    from dags.airflow import DAG
ModuleNotFoundError: No module named 'dags'
[2025-10-06T04:35:53.908+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T04:35:53.937+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.087 seconds
[2025-10-06T04:36:24.340+0000] {processor.py:161} INFO - Started process (PID=85) to work on /opt/airflow/dags/airflow.py
[2025-10-06T04:36:24.341+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T04:36:24.345+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:36:24.344+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T04:36:24.365+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:36:24.361+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 2, in <module>
    from dags.airflow import DAG
ModuleNotFoundError: No module named 'dags'
[2025-10-06T04:36:24.366+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T04:36:24.395+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.062 seconds
[2025-10-06T04:36:54.829+0000] {processor.py:161} INFO - Started process (PID=92) to work on /opt/airflow/dags/airflow.py
[2025-10-06T04:36:54.830+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T04:36:54.832+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:36:54.832+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T04:36:54.850+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:36:54.846+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 2, in <module>
    from dags.airflow import DAG
ModuleNotFoundError: No module named 'dags'
[2025-10-06T04:36:54.851+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T04:36:54.880+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.058 seconds
[2025-10-06T04:37:25.470+0000] {processor.py:161} INFO - Started process (PID=99) to work on /opt/airflow/dags/airflow.py
[2025-10-06T04:37:25.477+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T04:37:25.487+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:37:25.486+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T04:37:25.664+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:37:25.623+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 2, in <module>
    from dags.airflow import DAG
ModuleNotFoundError: No module named 'dags'
[2025-10-06T04:37:25.672+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T04:37:25.726+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.286 seconds
[2025-10-06T04:37:55.860+0000] {processor.py:161} INFO - Started process (PID=106) to work on /opt/airflow/dags/airflow.py
[2025-10-06T04:37:55.862+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T04:37:55.867+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:37:55.867+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T04:37:55.901+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:37:55.894+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 2, in <module>
    from dags.airflow import DAG
ModuleNotFoundError: No module named 'dags'
[2025-10-06T04:37:55.903+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T04:37:55.937+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.093 seconds
[2025-10-06T04:38:26.279+0000] {processor.py:161} INFO - Started process (PID=113) to work on /opt/airflow/dags/airflow.py
[2025-10-06T04:38:26.281+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T04:38:26.283+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:38:26.283+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T04:38:26.312+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:38:26.306+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 2, in <module>
    from dags.airflow import DAG
ModuleNotFoundError: No module named 'dags'
[2025-10-06T04:38:26.314+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T04:38:26.340+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.070 seconds
[2025-10-06T04:38:56.679+0000] {processor.py:161} INFO - Started process (PID=120) to work on /opt/airflow/dags/airflow.py
[2025-10-06T04:38:56.680+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T04:38:56.682+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:38:56.682+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T04:38:56.703+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:38:56.697+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 2, in <module>
    from dags.airflow import DAG
ModuleNotFoundError: No module named 'dags'
[2025-10-06T04:38:56.705+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T04:38:56.734+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.063 seconds
[2025-10-06T04:39:27.149+0000] {processor.py:161} INFO - Started process (PID=127) to work on /opt/airflow/dags/airflow.py
[2025-10-06T04:39:27.151+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T04:39:27.154+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:39:27.153+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T04:39:27.168+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:39:27.164+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 2, in <module>
    from dags.airflow import DAG
ModuleNotFoundError: No module named 'dags'
[2025-10-06T04:39:27.169+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T04:39:27.194+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.049 seconds
[2025-10-06T04:39:58.580+0000] {processor.py:161} INFO - Started process (PID=134) to work on /opt/airflow/dags/airflow.py
[2025-10-06T04:39:58.582+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T04:39:58.584+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:39:58.583+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T04:39:58.602+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:39:58.599+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 2, in <module>
    from dags.airflow import DAG
ModuleNotFoundError: No module named 'dags'
[2025-10-06T04:39:58.604+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T04:39:58.630+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.057 seconds
[2025-10-06T04:40:29.042+0000] {processor.py:161} INFO - Started process (PID=141) to work on /opt/airflow/dags/airflow.py
[2025-10-06T04:40:29.043+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T04:40:29.047+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:40:29.046+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T04:40:29.070+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:40:29.065+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 2, in <module>
    from dags.airflow import DAG
ModuleNotFoundError: No module named 'dags'
[2025-10-06T04:40:29.072+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T04:40:29.108+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.076 seconds
[2025-10-06T04:41:00.543+0000] {processor.py:161} INFO - Started process (PID=148) to work on /opt/airflow/dags/airflow.py
[2025-10-06T04:41:00.544+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T04:41:00.547+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:41:00.546+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T04:41:00.559+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:41:00.556+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 2, in <module>
    from dags.airflow import DAG
ModuleNotFoundError: No module named 'dags'
[2025-10-06T04:41:00.560+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T04:41:00.584+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.046 seconds
[2025-10-06T04:42:28.523+0000] {processor.py:161} INFO - Started process (PID=83) to work on /opt/airflow/dags/airflow.py
[2025-10-06T04:42:28.526+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T04:42:28.531+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:42:28.530+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T04:42:28.561+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:42:28.553+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 2, in <module>
    from dags.airflow import DAG
ModuleNotFoundError: No module named 'dags'
[2025-10-06T04:42:28.564+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T04:42:28.602+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.091 seconds
[2025-10-06T04:42:59.057+0000] {processor.py:161} INFO - Started process (PID=90) to work on /opt/airflow/dags/airflow.py
[2025-10-06T04:42:59.059+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T04:42:59.062+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:42:59.061+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T04:42:59.086+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:42:59.080+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 2, in <module>
    from dags.airflow import DAG
ModuleNotFoundError: No module named 'dags'
[2025-10-06T04:42:59.088+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T04:42:59.120+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.070 seconds
[2025-10-06T04:43:29.468+0000] {processor.py:161} INFO - Started process (PID=97) to work on /opt/airflow/dags/airflow.py
[2025-10-06T04:43:29.469+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T04:43:29.471+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:43:29.471+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T04:43:29.490+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:43:29.486+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 2, in <module>
    from dags.airflow import DAG
ModuleNotFoundError: No module named 'dags'
[2025-10-06T04:43:29.492+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T04:43:29.513+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.050 seconds
[2025-10-06T04:43:59.955+0000] {processor.py:161} INFO - Started process (PID=104) to work on /opt/airflow/dags/airflow.py
[2025-10-06T04:43:59.957+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T04:43:59.960+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:43:59.959+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T04:43:59.985+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:43:59.978+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 2, in <module>
    from dags.airflow import DAG
ModuleNotFoundError: No module named 'dags'
[2025-10-06T04:43:59.987+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T04:44:00.016+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.068 seconds
[2025-10-06T04:44:30.449+0000] {processor.py:161} INFO - Started process (PID=111) to work on /opt/airflow/dags/airflow.py
[2025-10-06T04:44:30.453+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T04:44:30.469+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:44:30.468+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T04:44:30.585+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:44:30.558+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 2, in <module>
    from dags.airflow import DAG
ModuleNotFoundError: No module named 'dags'
[2025-10-06T04:44:30.589+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T04:44:30.623+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.188 seconds
[2025-10-06T04:45:01.021+0000] {processor.py:161} INFO - Started process (PID=118) to work on /opt/airflow/dags/airflow.py
[2025-10-06T04:45:01.023+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T04:45:01.027+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:45:01.026+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T04:45:01.058+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:45:01.051+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 2, in <module>
    from dags.airflow import DAG
ModuleNotFoundError: No module named 'dags'
[2025-10-06T04:45:01.062+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T04:45:01.106+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.096 seconds
[2025-10-06T04:45:31.626+0000] {processor.py:161} INFO - Started process (PID=125) to work on /opt/airflow/dags/airflow.py
[2025-10-06T04:45:31.632+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T04:45:31.637+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:45:31.636+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T04:45:31.677+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:45:31.668+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 2, in <module>
    from dags.airflow import DAG
ModuleNotFoundError: No module named 'dags'
[2025-10-06T04:45:31.680+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T04:45:31.734+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.121 seconds
[2025-10-06T04:46:02.081+0000] {processor.py:161} INFO - Started process (PID=132) to work on /opt/airflow/dags/airflow.py
[2025-10-06T04:46:02.083+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T04:46:02.087+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:46:02.086+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T04:46:02.116+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:46:02.111+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 2, in <module>
    from dags.airflow import DAG
ModuleNotFoundError: No module named 'dags'
[2025-10-06T04:46:02.119+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T04:46:02.155+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.086 seconds
[2025-10-06T04:46:32.566+0000] {processor.py:161} INFO - Started process (PID=139) to work on /opt/airflow/dags/airflow.py
[2025-10-06T04:46:32.571+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T04:46:32.576+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:46:32.575+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T04:46:32.606+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:46:32.597+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 2, in <module>
    from dags.airflow import DAG
ModuleNotFoundError: No module named 'dags'
[2025-10-06T04:46:32.608+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T04:46:32.646+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.092 seconds
[2025-10-06T04:47:03.201+0000] {processor.py:161} INFO - Started process (PID=146) to work on /opt/airflow/dags/airflow.py
[2025-10-06T04:47:03.203+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T04:47:03.206+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:47:03.205+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T04:47:03.228+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:47:03.223+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 2, in <module>
    from dags.airflow import DAG
ModuleNotFoundError: No module named 'dags'
[2025-10-06T04:47:03.231+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T04:47:03.261+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.070 seconds
[2025-10-06T04:47:33.674+0000] {processor.py:161} INFO - Started process (PID=153) to work on /opt/airflow/dags/airflow.py
[2025-10-06T04:47:33.675+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T04:47:33.679+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:47:33.678+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T04:47:33.701+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:47:33.694+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 2, in <module>
    from dags.airflow import DAG
ModuleNotFoundError: No module named 'dags'
[2025-10-06T04:47:33.702+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T04:47:33.734+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.068 seconds
[2025-10-06T04:48:04.127+0000] {processor.py:161} INFO - Started process (PID=154) to work on /opt/airflow/dags/airflow.py
[2025-10-06T04:48:04.128+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T04:48:04.132+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:48:04.132+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T04:48:04.162+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:48:04.152+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 2, in <module>
    from dags.airflow import DAG
ModuleNotFoundError: No module named 'dags'
[2025-10-06T04:48:04.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T04:48:04.192+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.073 seconds
[2025-10-06T04:48:34.643+0000] {processor.py:161} INFO - Started process (PID=161) to work on /opt/airflow/dags/airflow.py
[2025-10-06T04:48:34.644+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T04:48:34.646+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:48:34.646+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T04:48:34.662+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:48:34.659+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 2, in <module>
    from dags.airflow import DAG
ModuleNotFoundError: No module named 'dags'
[2025-10-06T04:48:34.663+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T04:48:34.690+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.053 seconds
[2025-10-06T04:49:05.123+0000] {processor.py:161} INFO - Started process (PID=168) to work on /opt/airflow/dags/airflow.py
[2025-10-06T04:49:05.124+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T04:49:05.127+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:49:05.126+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T04:49:05.141+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:49:05.138+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 2, in <module>
    from dags.airflow import DAG
ModuleNotFoundError: No module named 'dags'
[2025-10-06T04:49:05.143+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T04:49:05.167+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.049 seconds
[2025-10-06T04:49:35.620+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/airflow.py
[2025-10-06T04:49:35.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T04:49:35.624+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:49:35.624+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T04:49:35.641+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:49:35.638+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 2, in <module>
    from dags.airflow import DAG
ModuleNotFoundError: No module named 'dags'
[2025-10-06T04:49:35.643+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T04:49:35.668+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.053 seconds
[2025-10-06T04:50:06.051+0000] {processor.py:161} INFO - Started process (PID=183) to work on /opt/airflow/dags/airflow.py
[2025-10-06T04:50:06.053+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T04:50:06.056+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:50:06.055+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T04:50:06.073+0000] {logging_mixin.py:188} INFO - [2025-10-06T04:50:06.069+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 2, in <module>
    from dags.airflow import DAG
ModuleNotFoundError: No module named 'dags'
[2025-10-06T04:50:06.074+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T04:50:06.096+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.051 seconds
